name: Deploy

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.x"

      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: |
          hugo mod get
          hugo

      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          source: "public/*"
          target: "/var/www/erik-skopp"
          rm: true
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Create folder structure
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd /var/www/erik-skopp; mv public/* .; rm -rf public
